List strings = [
  'Language',
  'Phone numbers',
  'Maximum page size',
  'Undo Send',
  'Default reply behavior',
  'Hover actions',
  'Send and Archive',
  'Default text style',
  'Images',
  'Dynamic email',
  'Grammar',
  'Spelling',
  'Autocorrect',
  'Smart Compose',
  'Smart Compose personalization',
  'Conversation View',
];
List value = [
  "Gmail display language:\nChange language settings for other Google products Show all language options",
  'Default country code:',
  'Show ',
  'Send cancellation period:',
  'Reply\nReply all',
  'Enable hover actions\nDisable hover actions',
  'Show "Send & Archive" button in reply\nHide "Send & Archive" button in reply',
  'Always display external images - Learn more\nAsk before displaying external images ',
  'Enable dynamic email ',
  'Grammar suggestions on\nGrammar suggestions off',
  'Spelling suggestions on\nSpelling suggestions off',
  'Autocorrect on\nAutocorrect off',
  'Writing suggestions on\nWriting suggestions off',
  'Personalization on\nPersonalization off',
  'Conversation view on\nConversation view off',
  'Suggest emails to reply to',
];
