List strings = [
  'Language',
  'Phone numbers',
  'Maximum page size',
  'Undo Send',
  'Default reply behavior',
  'Hover actions',
  'Send and Archive',
  'Default text style',
  'Images',
  'Dynamic email',
  'Grammar',
  'Spelling',
  'Autocorrect',
  'Smart Compose',
  'Star',
  'Conversation View',
];
List value = [
  "Gmail display language:",
  'Default country code:',
  'Show ',
  'Send cancellation period:',
  'Reply\nReply all',
  'Enable hover actions\nDisable hover actions',
  'Show "Send & Archive" button in reply\nHide "Send & Archive" button in reply',
  '',
  'Enable dynamic email ',
  'Grammar suggestions on\nGrammar suggestions off',
  'Spelling suggestions on\nSpelling suggestions off',
  'Autocorrect on\nAutocorrect off',
  'Writing suggestions on\nWriting suggestions off',
  'Personalization on\nPersonalization off',
  '',
  'Suggest emails to reply to',
];
final fontFamily = [
  'Sans Serif',
  'Serif',
  'Fixed Width',
  'Wide',
  'Narrow',
];
final size = ['small', 'Normal', 'Large', 'Huge'];
final countryName = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'India'
];
List countryCode = [
  '93',
  '355',
  '213',
  '1-684',
  '376',
  '244',
  '	1-264',
  '672',
  '	1-268',
  '54',
  '374',
  '297',
  '61',
  '43',
  '994',
  '1-242',
  '973',
  '880',
  '1-246',
  '91'
];
